if(RUNTIME_HARDWARE_ETHERNET_TEST)
    set(application_source ${PROJECT_SOURCE_DIR}/platform/hal/tests/hardware_ethernet_test.cpp)
elseif(RUNTIME_HARDWARE_IO_TEST)
    set(application_source ${PROJECT_SOURCE_DIR}/platform/runtime/tests/hardware_io_test.cpp)
elseif(RUNTIME_HARDWARE_SELF_TEST)
    set(application_source ${PROJECT_SOURCE_DIR}/platform/runtime/tests/hardware_self_test.cpp)
else()
    set(application_source ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp)
endif()

target_sources(${PROJECT_NAME} PRIVATE ${application_source})
target_include_directories(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(${PROJECT_NAME} PRIVATE platform::hal pneumo::pneumo)
