# Discover CubeMX-generated peripherals, rather than maintaining a second list
# of enabled handles in the factories. Regeneration triggers reconfiguration.
function(hal_generate_serial_instances output_directory include_directory)
    file(MAKE_DIRECTORY "${output_directory}")
    foreach(kind spi uart)
        if(kind STREQUAL "spi")
            set(header "${include_directory}/spi.h")
            set(pattern "MX_SPI[1-6]_Init[ \t]*\\(")
        else()
            set(header "${include_directory}/usart.h")
            set(pattern "MX_(USART[1236]|UART[4578]|LPUART1)_UART_Init[ \t]*\\(")
        endif()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${header}")
        file(READ "${header}" contents)
        string(REGEX MATCHALL "${pattern}" matches "${contents}")
        list(REMOVE_DUPLICATES matches)
        set(entries "// Generated from CubeMX declarations. Do not edit.\n")
        foreach(match IN LISTS matches)
            if(kind STREQUAL "spi")
                string(REGEX REPLACE "MX_SPI([1-6])_Init.*" "\\1" number "${match}")
                if(NOT contents MATCHES "SPI_HandleTypeDef[ \t]+hspi${number}[^a-zA-Z0-9_]")
                    message(FATAL_ERROR "Missing handle for ${match} in ${header}")
                endif()
                string(APPEND entries "HAL_SPI_INSTANCE(${number})\n")
            else()
                string(REGEX REPLACE "(MX_[A-Z]+[0-9]+_UART_Init).*" "\\1" initialize "${match}")
                string(REGEX REPLACE "MX_(USART|UART|LPUART)([0-9]+)_UART_Init.*" "\\1;\\2" parts "${match}")
                list(GET parts 0 family)
                list(GET parts 1 number)
                if(family STREQUAL "LPUART")
                    set(id "Lpuart${number}")
                    set(handle "hlpuart${number}")
                elseif(family STREQUAL "USART")
                    set(id "Usart${number}")
                    set(handle "huart${number}")
                else()
                    set(id "Uart${number}")
                    set(handle "huart${number}")
                endif()
                if(NOT contents MATCHES "UART_HandleTypeDef[ \t]+${handle}[^a-zA-Z0-9_]")
                    message(FATAL_ERROR "Missing handle for ${match} in ${header}")
                endif()
                string(APPEND entries "HAL_UART_INSTANCE(${id}, ${handle}, ${initialize})\n")
            endif()
        endforeach()
        # configure_file avoids touching the output if its contents did not change.
        file(WRITE "${output_directory}/${kind}_instances.in" "${entries}")
        configure_file("${output_directory}/${kind}_instances.in"
                       "${output_directory}/${kind}_instances.inc" COPYONLY)
    endforeach()
endfunction()
