# Compile a patched build-directory copy; never alter the user's submodule.
function(runtime_patch_filex)
    set(source "${PROJECT_SOURCE_DIR}/external/filex/common/src/fx_directory_delete.c")
    set(patch_file "${PROJECT_SOURCE_DIR}/platform/runtime/libc/patches/filex-directory-delete.patch")
    set(output "${PROJECT_BINARY_DIR}/filex-patched/fx_directory_delete.c")
    set(original_hash "2c12037bc9845447f75a8e3d850584bc147d5fc7b1f84273fd0791f2a3780dca")
    set(fixed_hash "ae1e3d0246c86b82237c38c418de96920570f21ee80ff6e8d027ab223c5e20f5")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}" "${patch_file}")
    file(READ "${source}" contents)
    string(REGEX REPLACE "\n+$" "\n" contents "${contents}")
    string(SHA256 source_hash "${contents}")
    file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/filex-patched")
    if(source_hash STREQUAL original_hash)
        find_program(PATCH_EXECUTABLE NAMES patch REQUIRED)
        execute_process(COMMAND "${PATCH_EXECUTABLE}" --batch --fuzz=0 --silent
                        --output "${output}" "${source}" "${patch_file}"
                        RESULT_VARIABLE patch_result)
        if(NOT patch_result EQUAL 0)
            message(FATAL_ERROR "FileX directory deletion patch failed: ${patch_result}")
        endif()
    elseif(source_hash STREQUAL fixed_hash)
        file(WRITE "${output}" "${contents}")
    else()
        message(FATAL_ERROR "Unexpected FileX directory-delete source; review local changes or dependency revision before updating the patch")
    endif()
    file(READ "${output}" patched_contents)
    string(REGEX REPLACE "\n+$" "\n" patched_contents "${patched_contents}")
    string(SHA256 output_hash "${patched_contents}")
    if(NOT output_hash STREQUAL fixed_hash)
        message(FATAL_ERROR "FileX patched source checksum does not match the reviewed fix")
    endif()
    get_target_property(filex_sources filex SOURCES)
    list(FILTER filex_sources EXCLUDE REGEX "/fx_directory_delete\\.c$")
    set_property(TARGET filex PROPERTY SOURCES "${filex_sources};${output}")
endfunction()
